require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: disable
  Exclude:
    - "bin/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

#Layout/LineLength:
#Exclude:

Lint/SuppressedException:
  Exclude:
    - "test/**/*"
    - "lib/tooling_invoker/runc_wrapper.rb"
    - "lib/tooling_invoker/external_command.rb"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  # We probably want to bring this down but let's start here for now
  Max: 20
  Exclude:
    - "test/**/*"

Naming/PredicateName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/GuardClause:
  Exclude:
    - lib/exercism_config/environment.rb

Style/IfUnlessModifier:
  Exclude:
    - "lib/exercism_config/setup_dynamodb_client.rb"

Style/NumericPredicate:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

# I don't mind this being enabled if
# someone fixes all the fails.
Style/ClassAndModuleChildren:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/exercism-config.rb"

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/LambdaCall:
  EnforcedStyle: braces
